<?php

/*
 * NIN/BVN purchase concurrency worker (Phase 11 CP1): a separate PHP process
 * (own DB connection) that waits at a start barrier, then submits the same
 * confirmed NIN/BVN purchase through PurchaseService with the test-only
 * FakeProvider, printing one JSON line per call. It never prints the number,
 * which arrives in the IDENTITY_TEST_NUMBER environment variable (generated by
 * the test when it runs, never on the command line). Every other submission
 * spaces the number out, an equivalent input. Each call scripts neutral
 * generated fixture result fields for a succeeded answer (a NIN/BVN success
 * needs its result, Phase 11 CP2). Started only by
 * tests/Concurrency/PurchaseIdentityTest.php.
 *
 * Usage: php identity_worker.php <barrier> <user-id> <plan-id> <count> <key> <script-csv> <delay-ms>
 */

use App\Exceptions\Purchases\PurchaseException;
use App\Models\Plan;
use App\Models\User;
use App\Services\Purchases\PurchaseService;
use Illuminate\Contracts\Console\Kernel;
use Illuminate\Support\Facades\DB;
use Tests\Support\Providers\FakeProvider;

require __DIR__.'/../../vendor/autoload.php';
$app = require __DIR__.'/../../bootstrap/app.php';
$app->make(Kernel::class)->bootstrap();
config(['providers.drivers' => ['fake-provider' => FakeProvider::class]]);

[, $barrier, $userId, $planId, $count, $key, $script, $delay] = $argv;
$number = (string) getenv('IDENTITY_TEST_NUMBER');
FakeProvider::reset();
FakeProvider::$services = ['nin', 'bvn'];
FakeProvider::$delayMs = (int) $delay;

DB::connection()->getPdo();
touch($barrier.'.ready.'.getmypid());
$deadline = microtime(true) + 60;
while (! file_exists($barrier)) {
    if (microtime(true) > $deadline) {
        fwrite(STDERR, "barrier timeout\n");
        exit(2);
    }
    usleep(500);
}

$service = app(PurchaseService::class);
$user = User::findOrFail((int) $userId);
$plan = Plan::findOrFail((int) $planId);

for ($i = 0; $i < (int) $count; $i++) {
    FakeProvider::$purchaseScript = $script === '-' ? [] : explode(',', $script);
    FakeProvider::$resultScript = [FakeProvider::fixtureFields()];
    $input = $i % 2 === 0 ? $number : implode(' ', str_split($number, 4));
    try {
        $purchase = $service->purchase($user, $plan, $input, null, $key, null, true);
        echo json_encode(['result' => 'ok', 'purchase' => $purchase->id, 'status' => $purchase->status->value]), "\n";
    } catch (PurchaseException $e) {
        echo json_encode(['result' => 'refused', 'message' => $e->getMessage()]), "\n";
    } catch (Throwable $e) {
        echo json_encode(['result' => 'error', 'class' => $e::class]), "\n";
    }
}
