<?php

namespace App\Models;

use App\Support\Referrals\ReferralCodes;
use App\Support\Referrals\ReferralEligibility;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use LogicException;

/**
 * A customer's referral code (Phase 12): generated by the system, upper-case,
 * unique and permanent; never edited, reassigned or deleted. A code is never
 * created for an API User. If its owner later becomes an API User the code is
 * kept, hidden and unusable, and works again once they are eligible again.
 */
class ReferralCode extends Model
{
    public const UPDATED_AT = null;

    /** @var list<string> */
    protected $fillable = [];

    protected static function booted(): void
    {
        static::creating(fn (self $code) => $code->enforceInvariants());
        static::updating(fn () => throw new LogicException('Referral codes never change.'));
        static::deleting(fn () => throw new LogicException('Referral codes are never deleted.'));
    }

    /** @return array<string, string> */
    protected function casts(): array
    {
        return ['user_id' => 'integer'];
    }

    /** @return BelongsTo<User, $this> */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    private function enforceInvariants(): void
    {
        if (! is_string($this->code) || ! ReferralCodes::isWellFormed($this->code)) {
            throw new LogicException('A referral code is 8 upper-case characters from the referral code alphabet.');
        }
        $owner = User::find($this->user_id);
        if ($owner === null || ! ReferralEligibility::canRefer($owner)) {
            throw new LogicException('A referral code is created only for a Subscriber, Vendor or Affiliate.');
        }
    }
}
