<?php

use Illuminate\Support\Facades\Http;
use Tests\Support\Providers\FakeProvider;
use Tests\Support\Providers\HttpTestProvider;
use Tests\Support\Providers\ResultContract;
use Tests\Support\Providers\ResultProbeProvider;

/*
 * Phase 11 CP2: the result contract kit for NIN/BVN adapters
 * (tests/Support/Providers/ResultContract.php), separate from the Phase 10
 * adapter contract kit; CP4 extends it to Exam PIN adapters (no recipient;
 * the PIN and serial must never reach a message, provider reference or log).
 * The kit is checked against a test-only probe adapter that follows every
 * rule, and then breaks one rule at a time. Every HTTP call is faked; every
 * value is generated by the kit when it runs.
 */

beforeEach(function () {
    ResultProbeProvider::reset();
    FakeProvider::reset();
    Http::preventStrayRequests();
    // The broken probe logs generated values on purpose: the kit still sees every log event, but nothing reaches the log file.
    config(['logging.default' => 'null']);
});

/** The probe's invented "documentation" for a delivered result: items of name and text, the number echoed, optional media. */
function rcDelivered(): Closure
{
    return fn (string $service, string $call, array $values, string $number, ?string $media) => Http::response(array_filter([
        'status' => 'delivered',
        'id' => 'RP-'.$call.'-'.$service,
        'number' => $number,
        'items' => array_map(fn (string $value, int $i) => ['name' => 'Item '.($i + 1), 'text' => $value], $values, array_keys($values)),
        'media' => $media,
    ], fn ($value) => $value !== null));
}

describe('delivery', function () {
    it('accepts an adapter that maps the delivered text, drops media and keeps result data out of messages and logs', function () {
        expect(ResultContract::deliveryViolations(new ResultProbeProvider, rcDelivered()))->toBe([]);
    });

    it('names the rule a broken adapter breaks', function (Closure $break, string $rule) {
        $break();

        expect(ResultContract::deliveryViolations(new ResultProbeProvider, rcDelivered()))->toContain($rule);
    })->with([
        'success without the result' => [fn () => ResultProbeProvider::$withoutFields = true,
            'purchase() for nin on the delivered answer: reported success without the result fields (the purchase would stay unclear).'],
        'fixed text instead of the result' => [fn () => ResultProbeProvider::$ignoresItems = true,
            'query() for bvn on the delivered answer: the result fields do not carry the delivered result text.'],
        'result text in the message' => [fn () => ResultProbeProvider::$itemInMessage = true,
            "purchase() for bvn on the delivered answer: the outcome's message, error code or provider reference contains result data."],
        'the number in the provider reference' => [fn () => ResultProbeProvider::$numberInReference = true,
            "query() for nin on the delivered answer: the outcome's message, error code or provider reference contains the purchased number."],
        'the answer logged' => [fn () => ResultProbeProvider::$logsAnswer = true, 'A log entry contains result text.'],
        'media mapped' => [fn () => ResultProbeProvider::$mapsMedia = true,
            'purchase() for nin on the delivered answer with media: must be succeeded with the result, not unknown.'],
        'media slipped through in pieces' => [fn () => ResultProbeProvider::$splitsMedia = true,
            'query() for nin on the delivered answer with media: media reached the result fields (text only).'],
    ]);

    it('catches an adapter that logs the answer with its number and media', function () {
        ResultProbeProvider::$logsAnswer = true;

        expect(ResultContract::deliveryViolations(new ResultProbeProvider, rcDelivered()))
            ->toBe(['A log entry contains result text.', 'A log entry contains the purchased number.', 'A log entry contains media.']);
    });

    it('checks only purchase() when the adapter has no status check, and only its NIN/BVN services', function () {
        ResultProbeProvider::$canQuery = false;
        ResultProbeProvider::$services = ['data', 'bvn'];
        ResultProbeProvider::$withoutFields = true;

        expect(ResultContract::deliveryViolations(new ResultProbeProvider, rcDelivered()))->toBe([
            'purchase() for bvn on the delivered answer: reported success without the result fields (the purchase would stay unclear).',
            'purchase() for bvn on the delivered answer with media: reported success without the result fields (the purchase would stay unclear).',
        ]);
    });

    it('fakes every request and puts the original HTTP client back', function () {
        $before = Http::getFacadeRoot();

        ResultContract::deliveryViolations(new ResultProbeProvider, rcDelivered());
        ResultContract::unclearViolations(new ResultProbeProvider);

        expect(Http::getFacadeRoot())->toBe($before)
            ->and(config('providers.http.retry_sleep_ms'))->toBe(200);
    });
});

describe('unclear answers', function () {
    it('accepts an adapter that keeps every unclear answer unknown, without a result', function () {
        expect(ResultContract::unclearViolations(new ResultProbeProvider))->toBe([]);
    });

    it('catches an adapter that treats a server error as delivered', function () {
        ResultProbeProvider::$deliversOnServerError = true;

        expect(ResultContract::unclearViolations(new ResultProbeProvider))
            ->toContain('purchase() for nin on HTTP 500 with a JSON body: must be unknown, not succeeded.')
            ->toContain('purchase() for nin on HTTP 500 with a JSON body: carries result fields, which only come with a success.')
            ->toContain('query() for bvn on HTTP 503 without JSON: must be unknown, not succeeded.');
    });

    it('has nothing to check for adapters without NIN or BVN', function () {
        ResultProbeProvider::$services = ['data', 'airtime'];
        ResultProbeProvider::$withoutFields = true;

        expect(ResultContract::unclearViolations(new ResultProbeProvider))->toBe([])
            ->and(ResultContract::deliveryViolations(new ResultProbeProvider, rcDelivered()))->toBe([]);
    });
});

describe('production result policy', function () {
    it('holds for every adapter registered in config/providers.php', function () {
        $config = require base_path('config/providers.php');

        expect($config['drivers'])->toBeArray()
            ->and(ResultContract::productionViolations($config['drivers'], []))->toBe([]);
    });

    it('requires the documented delivered answer of a registered NIN/BVN adapter', function () {
        expect(ResultContract::productionViolations(['result_probe' => ResultProbeProvider::class], []))
            ->toBe(['result_probe: delivers NIN/BVN results, but the result contract test has no documented delivered answer for it.']);
    });

    it('applies both checks to a registered NIN/BVN adapter, and none to the others', function () {
        $drivers = ['result_probe' => ResultProbeProvider::class, 'fake-provider' => FakeProvider::class,
            'http-test-provider' => HttpTestProvider::class, 'missing' => 'App\\Nope'];

        expect(ResultContract::productionViolations($drivers, ['result_probe' => rcDelivered()]))->toBe([]);

        ResultProbeProvider::$itemInMessage = true;
        ResultProbeProvider::$deliversOnServerError = true;
        $violations = ResultContract::productionViolations($drivers, ['result_probe' => rcDelivered()]);
        expect($violations)
            ->toContain("result_probe: purchase() for nin on the delivered answer: the outcome's message, error code or provider reference contains result data.")
            ->toContain('result_probe: query() for bvn on HTTP 500 with a JSON body: must be unknown, not succeeded.')
            ->and(array_filter($violations, fn (string $violation) => ! str_starts_with($violation, 'result_probe: ')))->toBe([]);
    });
});

describe('Exam PIN (CP4)', function () {
    it('accepts an Exam PIN adapter that keeps the delivered PIN out of messages, references and logs, with no number to send', function () {
        ResultProbeProvider::$services = ['exam-pin'];
        $numbers = [];
        $delivered = function (string $service, string $call, array $values, string $number, ?string $media) use (&$numbers) {
            $numbers[] = $number;

            return rcDelivered()($service, $call, $values, $number, $media);
        };

        expect(ResultContract::deliveryViolations(new ResultProbeProvider, $delivered))->toBe([])
            ->and(ResultContract::unclearViolations(new ResultProbeProvider))->toBe([])
            ->and($numbers)->toHaveCount(4) // purchase() and query(), with and without media
            ->and(array_values(array_unique($numbers)))->toBe(['']);
    });

    it('names the rule a broken Exam PIN adapter breaks', function (Closure $break, string $rule) {
        ResultProbeProvider::$services = ['exam-pin'];
        $break();

        expect(ResultContract::deliveryViolations(new ResultProbeProvider, rcDelivered()))->toContain($rule);
    })->with([
        'the PIN in the provider reference' => [fn () => ResultProbeProvider::$itemInReference = true,
            "purchase() for exam-pin on the delivered answer: the outcome's message, error code or provider reference contains result data."],
        'the PIN in the message' => [fn () => ResultProbeProvider::$itemInMessage = true,
            "query() for exam-pin on the delivered answer: the outcome's message, error code or provider reference contains result data."],
        'success without the PIN' => [fn () => ResultProbeProvider::$withoutFields = true,
            'purchase() for exam-pin on the delivered answer: reported success without the result fields (the purchase would stay unclear).'],
        'fixed text instead of the PIN' => [fn () => ResultProbeProvider::$ignoresItems = true,
            'query() for exam-pin on the delivered answer: the result fields do not carry the delivered result text.'],
        'the answer logged' => [fn () => ResultProbeProvider::$logsAnswer = true, 'A log entry contains result text.'],
    ]);

    it('catches an Exam PIN adapter that treats a server error as delivered', function () {
        ResultProbeProvider::$services = ['exam-pin'];
        ResultProbeProvider::$deliversOnServerError = true;

        expect(ResultContract::unclearViolations(new ResultProbeProvider))
            ->toContain('purchase() for exam-pin on HTTP 500 with a JSON body: must be unknown, not succeeded.')
            ->toContain('query() for exam-pin on HTTP 503 without JSON: carries result fields, which only come with a success.');
    });

    it('requires the documented delivered answer of a registered Exam PIN adapter, and applies both checks to it', function () {
        ResultProbeProvider::$services = ['exam-pin'];
        expect(ResultContract::productionViolations(['result_probe' => ResultProbeProvider::class], []))
            ->toBe(['result_probe: delivers Exam PIN results, but the result contract test has no documented delivered answer for it.']);
        ResultProbeProvider::$services = ['nin', 'bvn', 'exam-pin'];
        expect(ResultContract::productionViolations(['result_probe' => ResultProbeProvider::class], []))
            ->toBe(['result_probe: delivers NIN/BVN/Exam PIN results, but the result contract test has no documented delivered answer for it.'])
            ->and(ResultContract::productionViolations(['result_probe' => ResultProbeProvider::class], ['result_probe' => rcDelivered()]))->toBe([]);

        ResultProbeProvider::$itemInReference = true;
        expect(ResultContract::productionViolations(['result_probe' => ResultProbeProvider::class], ['result_probe' => rcDelivered()]))
            ->toContain("result_probe: purchase() for exam-pin on the delivered answer: the outcome's message, error code or provider reference contains result data.")
            ->toContain("result_probe: query() for nin on the delivered answer: the outcome's message, error code or provider reference contains result data.");
    });
});
