<?php

namespace App\Support\Referrals;

/**
 * Referral codes (Phase 12, decision C1): 8 characters from A–Z and 0–9
 * without the look-alikes 0/O and 1/I, so 32 symbols. Codes are generated by
 * the system (never chosen or edited by the customer) and stored upper-case.
 * Typed input is case-insensitive: surrounding spaces are removed and letters
 * upper-cased, nothing else (no look-alike mapping), so a code that does not
 * match exactly is not valid.
 */
final class ReferralCodes
{
    public const ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';

    public const LENGTH = 8;

    private const PATTERN = '/\A[A-HJ-NP-Z2-9]{8}\z/';

    /** A new random code (cryptographically secure); uniqueness is the database's job. */
    public static function generate(): string
    {
        $code = '';
        for ($i = 0; $i < self::LENGTH; $i++) {
            $code .= self::ALPHABET[random_int(0, strlen(self::ALPHABET) - 1)];
        }

        return $code;
    }

    /** Typed input as it will be looked up: trimmed and upper-cased only. */
    public static function normalise(?string $input): string
    {
        return strtoupper(trim((string) $input));
    }

    public static function isWellFormed(string $code): bool
    {
        return preg_match(self::PATTERN, $code) === 1;
    }
}
